scrape_configs:
  - job_name: bambulab
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - bambulab-metrics-exporter:9109
        labels:
          instance: bambu-x1c
